DROP DATABASE IF EXISTS recipesi;
CREATE DATABASE recipesi;
USE recipesi;

-- Create the user table
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Insert data into the user table
INSERT INTO `user` (`username`, `password`) VALUES
('pero', 'trapero'),
('risto', 'traktoristo'),
('riki', 'm@rtin');

-- Create the group table
CREATE TABLE IF NOT EXISTS `group` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` varchar(255),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Insert data into the group table
INSERT INTO `group` (`name`, `description`) VALUES
('Family Recipes', 'A group for sharing favorite family recipes'),
('Baking Enthusiasts', 'A group for passionate baking enthusiasts'),
('Healthy Eaters', 'A group for exchanging healthy eating tips and recipes'),
('Vegetarian Delights', 'A group for sharing delicious vegetarian recipes'),
('International Cuisine', 'A group for exploring recipes from around the world');


-- Create the recipe table
CREATE TABLE IF NOT EXISTS `recipe` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `ingredients` text NOT NULL,
  `instructions` text NOT NULL,
  `group_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`group_id`) REFERENCES `group` (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Insert data into the recipe table
INSERT INTO `recipe` (`title`, `description`, `ingredients`, `instructions`, `group_id`, `user_id`) VALUES
-- Family Recipes
('Roast Chicken', 'Classic roasted chicken with herbs', '1 whole chicken, 2 tbsp olive oil, 2 tsp dried rosemary, 2 tsp dried thyme, 2 tsp garlic powder, salt and pepper to taste', '1. Preheat oven to 425°F. 2. Pat the chicken dry with paper towels. 3. Rub olive oil all over the chicken. 4. In a small bowl, combine dried rosemary, dried thyme, garlic powder, salt, and pepper. 5. Sprinkle the herb mixture over the chicken, rubbing it into the skin. 6. Place the chicken on a rack in a roasting pan. 7. Roast for about 1 hour or until the internal temperature reaches 165°F. 8. Let the chicken rest for 10-15 minutes before carving.', 1, 1),
('Lasagna', 'Classic Italian baked pasta dish', '12 lasagna noodles, 1 lb ground beef, 1 onion (chopped), 2 cloves garlic (minced), 2 cups marinara sauce, 2 cups ricotta cheese, 2 cups shredded mozzarella cheese, 1/2 cup grated Parmesan cheese, 2 tbsp olive oil, 1 tsp dried oregano, 1 tsp dried basil, salt and pepper to taste', '1. Cook lasagna noodles according to package instructions. 2. In a large skillet, brown ground beef over medium heat. 3. Add chopped onion and minced garlic, and cook until onion is translucent. 4. Stir in marinara sauce, dried oregano, dried basil, salt, and pepper. Simmer for 10 minutes. 5. Preheat oven to 375°F. 6. In a greased baking dish, layer cooked lasagna noodles, meat sauce, ricotta cheese, shredded mozzarella cheese, and grated Parmesan cheese. Repeat the layers. 7. Cover the dish with foil and bake for 30 minutes. 8. Remove the foil and bake for an additional 15 minutes or until the cheese is bubbly and golden. 9. Let the lasagna cool for 10-15 minutes before serving.', 1, 2),
('Chocolate Cake', 'Moist and decadent chocolate cake', '2 cups all-purpose flour, 1 3/4 cups sugar, 3/4 cup unsweetened cocoa powder, 2 tsp baking powder, 1 1/2 tsp baking soda, 1 tsp salt, 2 eggs, 1 cup milk, 1/2 cup vegetable oil, 2 tsp vanilla extract, 1 cup boiling water', '1. Preheat oven to 350°F. 2. Grease and flour two 9-inch round cake pans. 3. In a large bowl, combine flour, sugar, cocoa powder, baking powder, baking soda, and salt. 4. Add eggs, milk, vegetable oil, and vanilla extract. Beat on medium speed for 2 minutes. 5. Stir in boiling water (the batter will be thin). 6. Pour the batter evenly into the prepared pans. 7. Bake for 30-35 minutes or until a toothpick inserted into the center comes out clean. 8. Let the cakes cool in the pans for 10 minutes, then transfer them to a wire rack to cool completely. 9. Frost with your favorite chocolate frosting.', 1, 3),
('Chicken Parmesan', 'Breaded chicken cutlets with tomato sauce and cheese', '4 boneless, skinless chicken breasts, 1 cup breadcrumbs, 1/2 cup grated Parmesan cheese, 2 eggs (beaten), 2 cups marinara sauce, 2 cups shredded mozzarella cheese, 2 tbsp olive oil, 1 tsp dried basil, 1 tsp dried oregano, salt and pepper to taste', '1. Preheat oven to 375°F. 2. In a shallow dish, combine breadcrumbs, grated Parmesan cheese, dried basil, dried oregano, salt, and pepper. 3. Dip each chicken breast into beaten eggs, then coat with breadcrumb mixture. 4. Heat olive oil in a large skillet over medium heat. 5. Cook breaded chicken breasts for about 3 minutes on each side, until golden brown. 6. Transfer the chicken breasts to a baking dish. 7. Pour marinara sauce over the chicken breasts and sprinkle shredded mozzarella cheese on top. 8. Bake for 20-25 minutes or until the chicken is cooked through and the cheese is melted and bubbly. 9. Serve with spaghetti or a side salad.', 1, 3),
('Blueberry Pancakes', 'Fluffy and delicious blueberry pancakes', '1 1/2 cups all-purpose flour, 3 1/2 tsp baking powder, 1 tsp salt, 1 tbsp sugar, 1 1/4 cups milk, 1 egg, 3 tbsp melted butter, 1 cup fresh blueberries', '1. In a large bowl, whisk together flour, baking powder, salt, and sugar. 2. In a separate bowl, whisk together milk, egg, and melted butter. 3. Pour the wet ingredients into the dry ingredients and stir until just combined. 4. Gently fold in the blueberries. 5. Heat a greased griddle or non-stick skillet over medium heat. 6. Pour 1/4 cup of batter onto the griddle for each pancake. 7. Cook until bubbles form on the surface, then flip and cook the other side until golden brown. 8. Serve hot with maple syrup.', 1, 2),
-- Baking Enthusiasts
('Cinnamon Rolls', 'Soft and gooey cinnamon rolls with cream cheese frosting', '4 cups all-purpose flour, 1/4 cup granulated sugar, 2 1/4 tsp instant yeast, 1 tsp salt, 1 cup milk, 1/4 cup unsalted butter, 2 eggs, 1/2 cup packed brown sugar, 2 tbsp ground cinnamon, 1/4 cup unsalted butter (softened), 4 oz cream cheese (softened), 2 cups powdered sugar, 1 tsp vanilla extract', '1. In a large bowl, combine flour, granulated sugar, instant yeast, and salt. 2. In a small saucepan, heat milk and butter until the butter is melted. 3. Add the milk mixture and eggs to the dry ingredients. Stir until a dough forms. 4. Knead the dough on a lightly floured surface for about 5 minutes, until smooth and elastic. 5. Place the dough in a greased bowl, cover, and let rise for 1 hour or until doubled in size. 6. Roll out the dough into a rectangle. 7. Spread softened butter over the dough. Sprinkle brown sugar and cinnamon evenly. 8. Roll up the dough tightly and cut into 12 rolls. 9. Place the rolls in a greased baking dish. Cover and let rise for 30 minutes. 10. Preheat oven to 375°F. 11. Bake the rolls for 20-25 minutes or until golden brown. 12. In a small bowl, beat cream cheese, powdered sugar, and vanilla extract until smooth. 13. Spread the cream cheese frosting over the warm rolls. Serve and enjoy!', 2, 1),
('Banana Bread', 'Moist and flavorful banana bread', '2 cups all-purpose flour, 1 tsp baking soda, 1/4 tsp salt, 1/2 cup unsalted butter (softened), 1 cup granulated sugar, 2 large eggs, 4 ripe bananas (mashed), 1/4 cup milk, 1 tsp vanilla extract', '1. Preheat oven to 350°F. 2. Grease and flour a loaf pan. 3. In a medium bowl, whisk together flour, baking soda, and salt. 4. In a large bowl, cream together softened butter and granulated sugar until light and fluffy. 5. Beat in eggs, one at a time. 6. Mix in mashed bananas, milk, and vanilla extract. 7. Gradually add the dry ingredients to the wet ingredients, mixing until just combined. 8. Pour the batter into the prepared loaf pan. 9. Bake for 50-60 minutes or until a toothpick inserted into the center comes out clean. 10. Let the banana bread cool in the pan for 10 minutes, then transfer it to a wire rack to cool completely.', 2, 2),
('Apple Pie', 'Classic homemade apple pie', '2 pie crusts (store-bought or homemade), 6 cups peeled and sliced apples, 3/4 cup granulated sugar, 2 tbsp all-purpose flour, 1 tsp ground cinnamon, 1/4 tsp ground nutmeg, 1 tbsp lemon juice, 2 tbsp unsalted butter (cut into small pieces), 1 egg (beaten), 1 tbsp milk, 1 tbsp granulated sugar (for sprinkling)', '1. Preheat oven to 425°F. 2. Line a 9-inch pie plate with one pie crust. 3. In a large bowl, combine sliced apples, granulated sugar, flour, cinnamon, nutmeg, and lemon juice. Toss until the apples are evenly coated. 4. Pour the apple mixture into the prepared pie crust. Dot the top with butter pieces. 5. Place the second pie crust over the filling. Trim and seal the edges. 6. In a small bowl, whisk together beaten egg and milk. Brush the mixture over the top crust. 7. Sprinkle granulated sugar over the crust. 8. Cut a few slits in the top crust to allow steam to escape. 9. Place the pie on a baking sheet to catch any drips. 10. Bake for 40-45 minutes or until the crust is golden brown and the filling is bubbly. 11. Let the pie cool on a wire rack before serving.', 2, 1),
('Vanilla Cupcakes', 'Light and fluffy vanilla cupcakes with buttercream frosting', '1 1/2 cups all-purpose flour, 1 1/2 tsp baking powder, 1/4 tsp salt, 1/2 cup unsalted butter (softened), 1 cup granulated sugar, 2 large eggs, 1 tsp vanilla extract, 1/2 cup milk, 1/2 cup unsalted butter (softened), 2 cups powdered sugar, 2-3 tbsp milk, 1 tsp vanilla extract, food coloring (optional)', '1. Preheat oven to 350°F. 2. Line a cupcake pan with paper liners. 3. In a medium bowl, whisk together flour, baking powder, and salt. 4. In a large bowl, cream together softened butter and granulated sugar until light and fluffy. 5. Beat in eggs, one at a time, followed by vanilla extract. 6. Gradually add the dry ingredients to the wet ingredients, alternating with milk, beginning and ending with the dry ingredients. Mix until just combined. 7. Divide the batter evenly among the cupcake liners, filling each about 2/3 full. 8. Bake for 15-18 minutes or until a toothpick inserted into the center comes out clean. 9. Let the cupcakes cool in the pan for 5 minutes, then transfer them to a wire rack to cool completely. 10. In a medium bowl, beat softened butter until creamy. 11. Gradually add powdered sugar, milk, and vanilla extract, mixing until smooth and fluffy. 12. Add food coloring, if desired, and mix until well incorporated. 13. Frost the cooled cupcakes and decorate as desired.', 2, 2),
('Chocolate Chip Cookies', 'Classic homemade chocolate chip cookies', '2 1/4 cups all-purpose flour, 1 tsp baking soda, 1/2 tsp salt, 1 cup unsalted butter (softened), 3/4 cup granulated sugar, 3/4 cup packed brown sugar, 1 tsp vanilla extract, 2 large eggs, 2 cups semisweet chocolate chips, 1 cup chopped walnuts (optional)', '1. Preheat oven to 375°F. 2. In a medium bowl, whisk together flour, baking soda, and salt. 3. In a large bowl, cream together softened butter, granulated sugar, and brown sugar until light and fluffy. 4. Beat in vanilla extract and eggs, one at a time. 5. Gradually add the dry ingredients to the wet ingredients, mixing until just combined. 6. Stir in chocolate chips and chopped walnuts, if using. 7. Drop rounded tablespoons of dough onto ungreased baking sheets. 8. Bake for 9-11 minutes or until golden brown. 9. Let the cookies cool on the baking sheets for 2 minutes, then transfer them to a wire rack to cool completely.', 2, 1),
-- Health-conscious Eaters
('Quinoa Salad', 'Refreshing and nutritious quinoa salad', '1 cup quinoa, 2 cups water, 1 cucumber (diced), 1 red bell pepper (diced), 1/2 red onion (finely chopped), 1 cup cherry tomatoes (halved), 1/4 cup chopped fresh parsley, 1/4 cup chopped fresh mint, 1/4 cup olive oil, 2 tbsp lemon juice, salt and pepper to taste', '1. Rinse quinoa under cold water. 2. In a medium saucepan, bring water to a boil. Add quinoa and reduce heat to low. Cover and simmer for 15-20 minutes or until the water is absorbed and the quinoa is tender. 3. Fluff the quinoa with a fork and let it cool. 4. In a large bowl, combine cooled quinoa, diced cucumber, diced red bell pepper, finely chopped red onion, cherry tomatoes, chopped fresh parsley, and chopped fresh mint. 5. In a small bowl, whisk together olive oil, lemon juice, salt, and pepper. 6. Pour the dressing over the quinoa mixture and toss to combine. 7. Adjust seasoning if needed. 8. Serve chilled or at room temperature.', 3, 3),
('Stir-Fry Vegetables', 'Quick and healthy stir-fried vegetables', '2 cups mixed vegetables (such as broccoli florets, bell peppers, snap peas, carrots), 2 tbsp vegetable oil, 2 cloves garlic (minced), 1 tbsp soy sauce, 1 tbsp oyster sauce (optional), salt and pepper to taste', '1. Heat vegetable oil in a large skillet or wok over medium-high heat. 2. Add minced garlic and sauté for 1 minute until fragrant. 3. Add mixed vegetables to the skillet and stir-fry for 4-5 minutes, or until crisp-tender. 4. In a small bowl, whisk together soy sauce and oyster sauce (if using). 5. Pour the sauce over the vegetables and toss to coat evenly. 6. Season with salt and pepper to taste. 7. Continue cooking for an additional 1-2 minutes. 8. Remove from heat and serve hot as a side dish or over steamed rice or noodles.', 3, 1),
('Greek Salad', 'Light and refreshing Greek salad', '4 cups chopped romaine lettuce, 1 cup chopped cucumber, 1 cup cherry tomatoes (halved), 1/2 cup sliced red onion, 1/2 cup Kalamata olives, 1/2 cup crumbled feta cheese, 2 tbsp extra-virgin olive oil, 1 tbsp red wine vinegar, 1 tsp dried oregano, salt and pepper to taste', '1. In a large bowl, combine chopped romaine lettuce, chopped cucumber, cherry tomatoes, sliced red onion, Kalamata olives, and crumbled feta cheese. 2. In a small bowl, whisk together extra-virgin olive oil, red wine vinegar, dried oregano, salt, and pepper. 3. Drizzle the dressing over the salad and toss to coat evenly. 4. Adjust seasoning if needed. 5. Serve immediately as a light lunch or side salad.', 3, 2),
('Grilled Chicken Salad', 'Grilled chicken salad with fresh vegetables', '2 boneless, skinless chicken breasts, 4 cups mixed salad greens, 1 cup cherry tomatoes (halved), 1/2 cup sliced cucumber, 1/4 cup sliced red onion, 1/4 cup sliced black olives, 2 tbsp extra-virgin olive oil, 2 tbsp lemon juice, 1 clove garlic (minced), salt and pepper to taste', '1. Preheat grill to medium-high heat. 2. Season chicken breasts with salt and pepper. Grill for 6-8 minutes per side, or until cooked through. 3. Remove chicken from the grill and let it rest for 5 minutes. Slice the chicken into thin strips. 4. In a large bowl, combine mixed salad greens, cherry tomatoes, sliced cucumber, sliced red onion, and sliced black olives. 5. In a small bowl, whisk together extra-virgin olive oil, lemon juice, minced garlic, salt, and pepper. 6. Drizzle the dressing over the salad and toss to coat evenly. 7. Top the salad with grilled chicken strips. 8. Serve immediately as a light and protein-packed meal.', 3, 3),
-- Vegan Options
('Vegan Buddha Bowl', 'Nourishing and colorful vegan Buddha bowl', '1 cup cooked quinoa, 1 cup roasted sweet potatoes (cubed), 1 cup steamed broccoli florets, 1/2 cup sliced avocado, 1/2 cup shredded carrots, 1/4 cup sliced almonds, 2 tbsp tahini, 2 tbsp lemon juice, 1 tbsp maple syrup, salt and pepper to taste', '1. In a bowl or plate, arrange cooked quinoa, roasted sweet potatoes, steamed broccoli florets, sliced avocado, shredded carrots, and sliced almonds. 2. In a small bowl, whisk together tahini, lemon juice, maple syrup, salt, and pepper. 3. Drizzle the tahini dressing over the Buddha bowl. 4. Serve immediately and enjoy a wholesome vegan meal.', 4, 2),
('Chickpea Curry', 'Flavorful and satisfying chickpea curry', '1 can chickpeas (drained and rinsed), 1 onion (chopped), 2 cloves garlic (minced), 1 tbsp curry powder, 1 tsp ground cumin, 1/2 tsp ground turmeric, 1/4 tsp cayenne pepper (optional), 1 can diced tomatoes, 1 cup coconut milk, 2 tbsp chopped fresh cilantro, 2 tbsp vegetable oil, salt and pepper to taste', '1. Heat vegetable oil in a large skillet over medium heat. 2. Add chopped onion and minced garlic. Sauté for 2-3 minutes until the onion is translucent. 3. Add curry powder, ground cumin, ground turmeric, and cayenne pepper (if using). Stir for 1 minute to toast the spices. 4. Add chickpeas, diced tomatoes, and coconut milk to the skillet. Season with salt and pepper to taste. 5. Simmer the curry for 15-20 minutes, stirring occasionally, until the flavors are well combined and the sauce has thickened slightly. 6. Remove from heat and stir in chopped fresh cilantro. 7. Serve the chickpea curry over steamed rice or with naan bread.', 4, 1),
('Vegan Lentil Soup', 'Hearty and nutritious vegan lentil soup', '1 cup dried green lentils, 4 cups vegetable broth, 1 onion (chopped), 2 carrots (chopped), 2 celery stalks (chopped), 2 cloves garlic (minced), 1 can diced tomatoes, 2 tsp ground cumin, 1 tsp ground coriander, 1/2 tsp smoked paprika, 1 bay leaf, 2 tbsp chopped fresh parsley, 2 tbsp olive oil, salt and pepper to taste', '1. Rinse lentils under cold water and remove any debris. 2. In a large pot, heat olive oil over medium heat. 3. Add chopped onion, chopped carrots, chopped celery, and minced garlic. Sauté for 5 minutes until the vegetables are slightly softened. 4. Add diced tomatoes (with juices), ground cumin, ground coriander, smoked paprika, bay leaf, and rinsed lentils to the pot. Stir to combine. 5. Pour in vegetable broth and season with salt and pepper. 6. Bring the soup to a boil, then reduce heat to low. Cover and simmer for 25-30 minutes, or until the lentils are tender. 7. Remove the bay leaf and stir in chopped fresh parsley. 8. Adjust seasoning if needed. 9. Serve hot as a comforting and nourishing soup.', 4, 2),
('Vegan Black Bean Burgers', 'Delicious and protein-packed vegan black bean burgers', '2 cans black beans (drained and rinsed), 1/2 cup cooked quinoa, 1/4 cup chopped red onion, 1/4 cup chopped bell pepper, 2 cloves garlic (minced), 2 tbsp chopped fresh cilantro, 1 tbsp ground flaxseed mixed with 3 tbsp water, 1 tsp ground cumin, 1/2 tsp chili powder, 1/4 tsp smoked paprika, salt and pepper to taste, burger buns and toppings of your choice', '1. In a large bowl, mash black beans with a fork or potato masher until mostly mashed but with some whole beans remaining. 2. Add cooked quinoa, chopped red onion, chopped bell pepper, minced garlic, chopped fresh cilantro, flaxseed mixture, ground cumin, chili powder, smoked paprika, salt, and pepper to the bowl. Stir until well combined. 3. Shape the mixture into burger patties. 4. Heat a non-stick skillet over medium heat and lightly grease with cooking spray or oil. 5. Cook the burgers for 4-5 minutes per side, or until golden brown and heated through. 6. Toast burger buns if desired and assemble the burgers with your favorite toppings. 7. Serve hot and enjoy a flavorful vegan burger.', 4, 1),
-- Gluten-free Options
('Quinoa Stuffed Bell Peppers', 'Delicious and gluten-free stuffed bell peppers', '4 bell peppers (any color), 1 cup cooked quinoa, 1/2 cup black beans (drained and rinsed), 1/2 cup corn kernels (fresh or frozen), 1/2 cup diced tomatoes, 1/4 cup chopped fresh cilantro, 1/4 cup shredded cheddar cheese (optional), 1 tbsp olive oil, 1 tsp ground cumin, 1/2 tsp chili powder, salt and pepper to taste', '1. Preheat the oven to 375°F. 2. Cut the tops off the bell peppers and remove the seeds and membranes. 3. In a large bowl, combine cooked quinoa, black beans, corn kernels, diced tomatoes, chopped fresh cilantro, shredded cheddar cheese (if using), olive oil, ground cumin, chili powder, salt, and pepper. Stir until well combined. 4. Stuff the bell peppers with the quinoa mixture and place them in a baking dish. 5. Bake for 25-30 minutes, or until the bell peppers are tender and the filling is heated through. 6. Remove from the oven and let them cool for a few minutes before serving.', 5, 2),
('Zucchini Noodles with Pesto', 'Light and gluten-free zucchini noodles with pesto', '2-3 zucchini, 1 cup fresh basil leaves, 1/4 cup pine nuts, 2 cloves garlic, 1/4 cup grated Parmesan cheese (optional), 2 tbsp extra-virgin olive oil, 1 tbsp lemon juice, salt and pepper to taste', '1. Using a spiralizer or vegetable peeler, create zucchini noodles. Set aside. 2. In a food processor, combine fresh basil leaves, pine nuts, garlic, grated Parmesan cheese (if using), extra-virgin olive oil, lemon juice, salt, and pepper. Blend until smooth and creamy. 3. In a large skillet, heat a small amount of olive oil over medium heat. 4. Add the zucchini noodles and sauté for 2-3 minutes until tender but still crisp. 5. Remove the skillet from heat and add the pesto sauce to the zucchini noodles. Toss until the noodles are well coated. 6. Adjust seasoning if needed. 7. Serve immediately as a light and gluten-free pasta alternative.', 5, 3),
('Grilled Salmon with Asparagus', 'Grilled salmon with tender asparagus spears', '2 salmon fillets, 1 bunch asparagus, 2 tbsp olive oil, 2 cloves garlic (minced), 1 tsp lemon zest, 1 tbsp lemon juice, salt and pepper to taste', '1. Preheat the grill to medium-high heat. 2. In a small bowl, combine olive oil, minced garlic, lemon zest, lemon juice, salt, and pepper. 3. Brush the salmon fillets and asparagus spears with the olive oil mixture. 4. Place the salmon and asparagus on the grill. 5. Grill the salmon for 4-5 minutes per side, or until it flakes easily with a fork. 6. Grill the asparagus for 2-3 minutes, or until tender and slightly charred. 7. Remove the salmon and asparagus from the grill. 8. Serve hot as a flavorful and gluten-free main dish.', 5, 2);

-- Create the Chat table
CREATE TABLE IF NOT EXISTS `chat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`group_id`) REFERENCES `group` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create the message table
CREATE TABLE IF NOT EXISTS `message` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `chat_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `content` text NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`chat_id`) REFERENCES `chat` (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
